### ISSUE TITLE
WEB - HIGH - anteprime video

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#10]
Aggiungere le anteprime video nella lista dei vari esercizi con player tipo YouTube

- [x] scaricare i video da drive
- [x] aggiungere campo pathimg in tabella esercizi nullo così, se vuoto mostra img vuota
- [x] aggiungere per ogni record in db la sua il path della sua anteprima

**Comment by mauripdb** [comment]
@mattiangelelli le anteprime saranno solo delle immagine non saranno anteprime video tipo 3secondi di riproduzione

**Comment by mauripdb** [comment]
ok risolto il size della card materialize css ma sono stati aggiunti solo i balance

**Comment by mauripdb** [comment]
@mattiangelelli allora sono state caricate tutte le categorie rom, strength e balance... circa 4/5 anteprime non vengono caricate, non so bene perchè per il momento le metto da parte perchè abbiamo veramente tantissimo da fare

- manca per chiudere l'attività action observation e cues che devono essere caricate sia come 
    - db e mancano i codice youtube
