### ISSUE TITLE
WEB - HIGH - Aggiungere per il fisio la possibilità di creare una nuova scheda del paziente

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#11]
Nel Burger sotto pazienti aggiungere una nuova voce con scritto "Aggiungi paziente" per creare una nuova scheda, che rimanda alla scheda di dati con anagrafica, valutazioni eccetera

**Comment by mauripdb** [comment]
@mattiangelelli chiusa con redirezione alla pagina cartella clinica del paziente appena creato
