### ISSUE TITLE
 WEB - MOBILE - HIGH - Bug quando premo sulla striscia colorata nel calendario

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#12]
Quando premo striscia colorata nel calendario dopo aver associato gli esercizi nel calendario mi dice che la pagina non è disponibile

**Comment by mattiangelelli** [comment]
Forse perché non e collegato con la parte MOBILE del feedback, non saprei. Però quando il fisio ci schiaccia sopra e non è ancora terminata ma sessione degli esercizi (ovvero il paziente non li ha ancora fatti) dovrei poter vedere l'elenco degli esercizi che gli go messo per eventualmente poterlo modificare.

**Comment by mauripdb** [comment]
fixatoooooooo il problema era nel usercalendarexercise()
