### ISSUE TITLE
WEB - LOW - Pagina iniziale

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#14]
Quando vado nel sito come prima pagina (prima ancora di fare il Log in) vorrei che si vedesse la scritta ParkinsHome in alto in bianco un po' più spostata dal borso sx. Al posto di "Hello People" scrivere benvenuto su ParkinsHome (al centro della pagina) e sotto mettere l'immagine con il logo che ha fatto Davi Fioritz (che se sono riuscito ti ho allegato).
Sotto l'immagine (oltre a mantenere la scritta come l'ha fatta Davi e se magari puoi copiarla uguale anche in alto nella parte blu), metterei due righe di spiegazione di cosa è il progetto e cosa fa, o anche solo uno slogan, tipo
"Tu al centro della riabilitazione" o "la riabilitazione a casa tua".

![ParkinsHome logo](https://user-images.githubusercontent.com/51284552/58895004-4b4ca580-86f3-11e9-850d-9802835ece87.jpeg)

**Comment by mauripdb** [comment]
issue chiusa manca il testo da mettere sul progetto.
