### ISSUE TITLE
WEB - LOW - Pagina dopo il Log-in

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#15]
Nella pagina dopo il log-in (Oltre a cambiare con "Benvenuto" al posto di "hello" prima del nome di chi si logga (che ovviamente poi sarò io)) ti propongo tre opzioni, valuta tu in base al livello di difficoltà.
1) metterei magari la possibilità di vedere uno storico delle attività, ovvero magari vedere in evidenza quali sono le schede dei pazienti che hanno appena usato l'app o fatto gli esercizi, magari scritti in modo carino, in modo che cliccandoci sopra possa già direttamente vedere che cosa ha fatto il paziente.
2) mettiamo una pagina introduttiva in cui spieghiamo il progetto in breve con due righe 
3) mettiamo la possibilità di avere delle schedine rettangolari nella pagine che sarebbero le stesse che ci sono nel Burger in alto, in modo che il fisio possa cliccare li sopra ed andare direttamente in quello che gli interessa senza aprire il menù.

A me piace di più la 1 ma direi che questa parte non è essenziale.

**Comment by mauripdb** [comment]
ok per il momento ho caricato un lorem ipsum con un impaginazione della seconda opzione costava meno. tanto in realtà è la tua dashboard quindi posso anche aggiornartela durante la sperimentazione. 
ps: la prima opzione la preferisco anche io

**Comment by mattiangelelli** [comment]
OK GUARDA che ci sono anche due issue nuove che h messo ieri che sono abbastanza importanti e che non sono filtrate come High

Mattia Angelelli

________________________________
Da: Maurizio <notifications@github.com>
Inviato: Sunday, June 30, 2019 10:37:00 PM
A: mauripdb/web-recognmm
Cc: mattiangelelli; Author
Oggetto: Re: [mauripdb/web-recognmm] WEB - LOW - Pagina dopo il Log-in (#15)


ok per il momento ho caricato un lorem ipsum con un impaginazione della seconda opzione costava meno. tanto in realtà è la tua dashboard quindi posso anche aggiornartela durante la sperimentazione.
ps: la prima opzione la preferisco anche io
