### ISSUE TITLE
WEB - LOW - Nella scheda Lista (Dentro il Burger, click Esercizi -> Lista)

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#16]
Anche questo punto non ha la massima priorità.

Quando arrivi qui nel modo in cui ti ho scritto (ovvero passando dal Burger e cliccando sotto esercizi e poi lista) non ha senso che si vedano i + perchè tanto non sono ancora in nessuna scheda relativa a nessun paziente e quindi non posso assegnarli nulla.
Piuttosto io metterei da qui la possibilità di eliminare alcuni esercizi proprio dalla lista (perchè magari vecchi o obsoleti) e di aggiungerne altri (magari caricandoli proprio dal pc che li passa sul server).
Quindi farei così (ovviamente se non è troppo lavoro): metterei al posto del bottone + un bottone con il - e quando il fisio lo schiaccia appare un messaggio con scritto "vuoi davvero eliminare il video selezionato?", se clicco si il video viene rimosso e non è più presente nella lista.
In alto al posto del bottone "Back to calendar" metterei un altro bottone "Charge new video" che da la possiblità di caricare nuovi v ideo nella lista.

**Comment by mauripdb** [comment]
questa è risolta in parte facendo solamente vedere gli esercizi senza il + al massimo la riapriamo dopo
