### ISSUE TITLE
WEB - LOW - C'è bisogno di un ritorno...

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#20]
Sotto la scheda del paziente, quando clicco su "calendario" sotto trattamento mi manda al calendario, e questo è perfetto.
Però dal calendario del paziente mi serve un tasto per poter tornare dove ero prima senza dover fare di nuovo tutto il giro dal Burger.

**Comment by mauripdb** [comment]
@mattiangelelli per quanto riguarda questa ho risolto abilitando al terapeuta loggato il ritorno cliccando in alto a sinistra sulla scritta parkinshom affianco al burger menu
