### ISSUE TITLE
WEB - HIGH - Aggiungere anche i video della categoria Action Observation

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#34]
Li devo sncora comprimere, l'unico problema è che sono in verticale perché sono video di una tesi precedente. Però pazienza ci arrangiamo così

**Comment by mauripdb** [comment]
@mattiangelelli aggiunti i video su ytube devono essere mappati nel database

**Comment by mattiangelelli** [comment]
Mauri ti ho detto di non aggiungerli quelli dell’action observation perché alcuni sono ancora da modificare. Aggiungi solo i cues.
Quelli che modifico sono sotto la cartella supino dentro Action Observation (gli altri restano uguale). Quindi cancella solo quelli da youtube

Mattia Angelelli

________________________________
Da: Maurizio <notifications@github.com>
Inviato: Monday, June 24, 2019 5:10:41 PM
A: mauripdb/web-recognmm
Cc: mattiangelelli; Mention
Oggetto: Re: [mauripdb/web-recognmm] WEB - HIGH - Aggiungere anche i video della categoria Action Observation (#34)


@mattiangelelli<https://github.com/mattiangelelli> aggiunti i video su ytube devono essere mappati nel database
