### ISSUE TITLE
MOBILE - WEB - Nuovo paziente/login

### ISSUE THREAD

**Issue by mattiangelelli** [mauripdb/web-recognmm#35]
Non so se questa cosa sia già fatta o meno ma te la scrivo lo stesso. Quando aggiungi la possibilità di creare una nuova scheda del paziente dalla parte web (che ti ho messo in un altra issue) bisognerebbe che si creasse in qualche modo anche la login personale di quello specifico paziente, che può utilizzare per accedere poi all'app. Non so se sta cosa la faccia già automaticamente quando aggiungi una nuova scheda paziente o no.. non so. 
Però tipo se io voglio iniziare la sperimentazione io aggiungo tot pazienti e di ognuno mi dà il login e la pw che poi io gli do in modo che possano iniziare a fare gli esercizi

**Comment by mauripdb** [comment]
@mattiangelelli  allora al momento non possiamo avere più dottori, ma ogni paziente ha la propria login e accede con i propri dati, quindi il modulo di login/autenticazione alla piattaforma è uguale per tutti ma con credenziali differenti. ok?

**Comment by mauripdb** [comment]
@mattiangelelli ci riserviamo per il dopo la possibilità di avere multipli terapeuti

**Comment by mattiangelelli** [comment]
Si mauri era quello che dicevo io, non volevo la possibilità di entrare per più terapisti ma che ogni paziente avesse la propria scheda con la propria login. Cioè che dalla app entrasse con il suo nome utente e la sua password e che il fisio quando entra nella parte web vede i progressi di tutti i pazienti che sono messi sotto la loro scheda

Mattia Angelelli

________________________________
Da: Maurizio <notifications@github.com>
Inviato: Sunday, June 23, 2019 5:34:47 PM
A: mauripdb/web-recognmm
Cc: mattiangelelli; Mention
Oggetto: Re: [mauripdb/web-recognmm] MOBILE - WEB - Nuovo paziente/login (#35)


@mattiangelelli<https://github.com/mattiangelelli> allora al momento non possiamo avere più dottori, ma ogni paziente ha la propria login e accede con i propri dati, quindi il modulo di login/autenticazione alla piattaforma è uguale per tutti ma con credenziali differenti. ok?
